### ISSUE TITLE
remote open("/file.yml"): Permission denied

### ISSUE THREAD

**Issue by stefanocog** [luzifer-docker/sftp-share#3]
Hi, thanks for container,
i login correctly with `sftp -P 2222:22 foo@ip_container` but when i try to copy file into container i have this error

```
sftp> put file.yml 
Uploading file.yml to /file.yml
remote open("/file.yml"): Permission denied
```

I have changed permission of folder `/data` to user `foo` into container and work but i need automatize this container and i have write this Dockerfile:

```
FROM luzifer/sftp-share
RUN chown -R $USER.$USER /data
```

But when build the container i receive this error:

```
Step 1 : RUN chown -R $USER.$USER /data
 ---> Running in cb678c69a2ad
chown: invalid user: 'share.share'
```

My docker-compose.yml is that:

```
sftp:
 build: sftp/
 volumes:
  - /host/path:/data
 ports:
  - "2222:22"
 environment:
  - USER=foo
  - PASS=password
```

Thanks
